/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BoardBoardIdLazyImport = createFileRoute('/board/$boardId')()

// Create/Update Routes

const BoardBoardIdLazyRoute = BoardBoardIdLazyImport.update({
  path: '/board/$boardId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/board/$boardId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ BoardBoardIdLazyRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/board/$boardId"
      ]
    },
    "/board/$boardId": {
      "filePath": "board/$boardId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
