/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BoardIndexLazyImport = createFileRoute('/board/')()
const BoardBoardIdLazyImport = createFileRoute('/board/$boardId')()

// Create/Update Routes

const BoardIndexLazyRoute = BoardIndexLazyImport.update({
  path: '/board/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/board/index.lazy').then((d) => d.Route))

const BoardBoardIdLazyRoute = BoardBoardIdLazyImport.update({
  path: '/board/$boardId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/board/$boardId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  BoardBoardIdLazyRoute,
  BoardIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/board/$boardId",
        "/board/"
      ]
    },
    "/board/$boardId": {
      "filePath": "board/$boardId.lazy.tsx"
    },
    "/board/": {
      "filePath": "board/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
